-- MySQL Script generated by MySQL Workbench
-- Wed Apr 27 11:28:53 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`user` ;

CREATE TABLE IF NOT EXISTS `mydb`.`user` (
  `iduser` INT NOT NULL,
  `first_name` VARCHAR(45) NULL,
  `last_name` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `date_to_admission` DATE NULL,
  `university` VARCHAR(70) NULL,
  `rating` INT NULL,
  `speciality` VARCHAR(45) NULL,
  PRIMARY KEY (`iduser`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`admin`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`admin` ;

CREATE TABLE IF NOT EXISTS `mydb`.`admin` (
  `idadmin` INT NOT NULL,
  `user_iduser` INT NOT NULL,
  `spec_pass` VARCHAR(45) NULL,
  `is_admin` TINYINT NULL,
  PRIMARY KEY (`idadmin`),
  INDEX `fk_admin_user_idx` (`user_iduser` ASC) VISIBLE,
  CONSTRAINT `fk_admin_user`
    FOREIGN KEY (`user_iduser`)
    REFERENCES `mydb`.`user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`leaderboard_entry`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`leaderboard_entry` ;

CREATE TABLE IF NOT EXISTS `mydb`.`leaderboard_entry` (
  `idleaderboard_entry` INT NOT NULL,
  `user_iduser` INT NOT NULL,
  `rating_delta` INT NULL,
  PRIMARY KEY (`idleaderboard_entry`),
  INDEX `fk_leaderboard_entry_user1_idx` (`user_iduser` ASC) VISIBLE,
  CONSTRAINT `fk_leaderboard_entry_user1`
    FOREIGN KEY (`user_iduser`)
    REFERENCES `mydb`.`user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`leaderboard_timestamp`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`leaderboard_timestamp` ;

CREATE TABLE IF NOT EXISTS `mydb`.`leaderboard_timestamp` (
  `idleaderboard_timestamp` INT NOT NULL,
  `user_iduser` INT NOT NULL,
  `rating` INT NULL,
  PRIMARY KEY (`idleaderboard_timestamp`),
  INDEX `fk_leaderboard_timestamp_user1_idx` (`user_iduser` ASC) VISIBLE,
  CONSTRAINT `fk_leaderboard_timestamp_user1`
    FOREIGN KEY (`user_iduser`)
    REFERENCES `mydb`.`user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`verification_request`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`verification_request` ;

CREATE TABLE IF NOT EXISTS `mydb`.`verification_request` (
  `idverification_request` INT NOT NULL,
  `user_iduser` INT NOT NULL,
  `status` TINYINT NULL,
  PRIMARY KEY (`idverification_request`),
  INDEX `fk_verification_request_user1_idx` (`user_iduser` ASC) VISIBLE,
  CONSTRAINT `fk_verification_request_user1`
    FOREIGN KEY (`user_iduser`)
    REFERENCES `mydb`.`user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`subject_tag`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`subject_tag` ;

CREATE TABLE IF NOT EXISTS `mydb`.`subject_tag` (
  `idsubject_tag` INT NOT NULL,
  `subject_name` VARCHAR(45) NULL,
  PRIMARY KEY (`idsubject_tag`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`question`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`question` ;

CREATE TABLE IF NOT EXISTS `mydb`.`question` (
  `idquestion` INT NOT NULL,
  `user_iduser` INT NOT NULL,
  `subject_tag_idsubject_tag` INT NOT NULL,
  `header` VARCHAR(90) NULL,
  `description` TEXT(1000) NULL,
  `date` DATE NULL,
  `votesup` INT NULL,
  `votesdown` INT NULL,
  PRIMARY KEY (`idquestion`),
  INDEX `fk_question_user1_idx` (`user_iduser` ASC) VISIBLE,
  INDEX `fk_question_subject_tag1_idx` (`subject_tag_idsubject_tag` ASC) VISIBLE,
  CONSTRAINT `fk_question_user1`
    FOREIGN KEY (`user_iduser`)
    REFERENCES `mydb`.`user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_question_subject_tag1`
    FOREIGN KEY (`subject_tag_idsubject_tag`)
    REFERENCES `mydb`.`subject_tag` (`idsubject_tag`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`answer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`answer` ;

CREATE TABLE IF NOT EXISTS `mydb`.`answer` (
  `idanswer` INT NOT NULL,
  `question_idquestion` INT NOT NULL,
  `user_iduser` INT NOT NULL,
  `description` TEXT(1000) NULL,
  `date` DATE NULL,
  `votesup` INT NULL,
  `votesdown` INT NULL,
  PRIMARY KEY (`idanswer`),
  INDEX `fk_answer_question1_idx` (`question_idquestion` ASC) VISIBLE,
  INDEX `fk_answer_user1_idx` (`user_iduser` ASC) VISIBLE,
  CONSTRAINT `fk_answer_question1`
    FOREIGN KEY (`question_idquestion`)
    REFERENCES `mydb`.`question` (`idquestion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_answer_user1`
    FOREIGN KEY (`user_iduser`)
    REFERENCES `mydb`.`user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`file_link`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`file_link` ;

CREATE TABLE IF NOT EXISTS `mydb`.`file_link` (
  `idfile_link` INT NOT NULL,
  `file_path` VARCHAR(90) NULL,
  PRIMARY KEY (`idfile_link`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`file_question`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`file_question` ;

CREATE TABLE IF NOT EXISTS `mydb`.`file_question` (
  `idfile_question` INT NOT NULL,
  `file_link_idfile_link` INT NOT NULL,
  `question_idquestion` INT NOT NULL,
  PRIMARY KEY (`idfile_question`),
  INDEX `fk_file_question_file_link1_idx` (`file_link_idfile_link` ASC) VISIBLE,
  INDEX `fk_file_question_question1_idx` (`question_idquestion` ASC) VISIBLE,
  CONSTRAINT `fk_file_question_file_link1`
    FOREIGN KEY (`file_link_idfile_link`)
    REFERENCES `mydb`.`file_link` (`idfile_link`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_file_question_question1`
    FOREIGN KEY (`question_idquestion`)
    REFERENCES `mydb`.`question` (`idquestion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`file_answer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`file_answer` ;

CREATE TABLE IF NOT EXISTS `mydb`.`file_answer` (
  `idfile_answer` INT NOT NULL,
  `file_link_idfile_link` INT NOT NULL,
  `answer_idanswer` INT NOT NULL,
  PRIMARY KEY (`idfile_answer`),
  INDEX `fk_file_answer_file_link1_idx` (`file_link_idfile_link` ASC) VISIBLE,
  INDEX `fk_file_answer_answer1_idx` (`answer_idanswer` ASC) VISIBLE,
  CONSTRAINT `fk_file_answer_file_link1`
    FOREIGN KEY (`file_link_idfile_link`)
    REFERENCES `mydb`.`file_link` (`idfile_link`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_file_answer_answer1`
    FOREIGN KEY (`answer_idanswer`)
    REFERENCES `mydb`.`answer` (`idanswer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`file_request`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`file_request` ;

CREATE TABLE IF NOT EXISTS `mydb`.`file_request` (
  `idfile_request` INT NOT NULL,
  `file_link_idfile_link` INT NOT NULL,
  `verification_request_idverification_request` INT NOT NULL,
  PRIMARY KEY (`idfile_request`),
  INDEX `fk_file_request_file_link1_idx` (`file_link_idfile_link` ASC) VISIBLE,
  INDEX `fk_file_request_verification_request1_idx` (`verification_request_idverification_request` ASC) VISIBLE,
  CONSTRAINT `fk_file_request_file_link1`
    FOREIGN KEY (`file_link_idfile_link`)
    REFERENCES `mydb`.`file_link` (`idfile_link`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_file_request_verification_request1`
    FOREIGN KEY (`verification_request_idverification_request`)
    REFERENCES `mydb`.`verification_request` (`idverification_request`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
